### ISSUE TITLE
Finalize the interface; make it work similar to superagent-mock

### ISSUE THREAD

**Issue by j3parker** [Brightspace/superagent-d2l-session-auth#22]
https://github.com/M6Web/superagent-mock

    var api = require('superagent-d2l-session-auth')(require('superagent'));
    
    api
        .get('/d2l/api/1.0/users/whoami')
        .end( ... );

**Comment by dlockhart** [comment]
I still think you're going to want them to explicitly tell you which requests they'd like to use auth for:

    var request = require('superagent');
    var auth = require('superagent-d2l-session-auth')(request);
    request
      .get('myAPI')
      .use(auth);

**Comment by j3parker** [comment]
Ah, that's fair. I like what you did in the CORS library.
