### ISSUE TITLE
Need strategy for "refreshcookie" and the CDN

### ISSUE THREAD

**Issue by j3parker** [Brightspace/superagent-d2l-session-auth#30]
Thanks @smajkic for noticing this.

It currently doesn't break anything (because the LE/etc. APIs fallback to d2lSecureSessionVal etc. if OAuth tokens are missing) but the library is trying to do the "refreshcookie" with a relative path.

Two things need to happen, approximately:

- The refreshcookie route in the LE should use the same CORS logic as the APIs (maybe make it an API? Hmmm)
- This library should not use a relative URL for refreshcookie. How it determines the right URL is an interesting question... @dlockhart might have ideas

**Comment by dlockhart** [comment]
@j3parker, can it use the host of the request being made?
